# Generated by Django 4.2.17 on 2025-03-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0132_partparametertemplate_selectionlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='pharm_description',
            field=models.CharField(blank=True, help_text='Part pharm description (optional)', max_length=250, verbose_name='Pharm Description'),
        ),
    ]
