# Generated by Django 4.2.17 on 2025-03-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0133_part_pharm_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='pharm_description',
        ),
        migrations.AddField(
            model_name='part',
            name='acquistion_unit_cost',
            field=models.FloatField(blank=True, default=0, help_text='Cost per unit', verbose_name='Acquistion Unit Cost'),
        ),
        migrations.AddField(
            model_name='part',
            name='active_ingredient',
            field=models.BooleanField(default=False, help_text='Active Pharmaceutical Ingredient', verbose_name='Active Ingredient'),
        ),
        migrations.AddField(
            model_name='part',
            name='auxillary_labels',
            field=models.CharField(choices=[('May Cause Drowsiness', 'May Cause Drowsiness'), ('Shake Well', 'Shake Well'), ('Take with food', 'Take with food'), ('', '')], default='', help_text='Supplemental information', max_length=100, verbose_name='Auxillary Labels'),
        ),
        migrations.AddField(
            model_name='part',
            name='consumable',
            field=models.BooleanField(default=False, help_text='Tracked ingredient with no expiration date', verbose_name='Consumable'),
        ),
        migrations.AddField(
            model_name='part',
            name='flavored',
            field=models.BooleanField(default=False, help_text='Flavor added', verbose_name='Flavored'),
        ),
        migrations.AddField(
            model_name='part',
            name='has_activity_factor',
            field=models.BooleanField(default=False, help_text='Ingredient with varied activity', verbose_name='Activity Factor'),
        ),
        migrations.AddField(
            model_name='part',
            name='has_pack_stat',
            field=models.BooleanField(default=False, help_text='Ingredient with pack stats', verbose_name='Has Pack Stat'),
        ),
        migrations.AddField(
            model_name='part',
            name='hazardous',
            field=models.BooleanField(default=False, help_text='Is this a hazardous drug', verbose_name='Hazardous'),
        ),
        migrations.AddField(
            model_name='part',
            name='ndc',
            field=models.CharField(blank=True, help_text='FDA National Drug Code', max_length=15, verbose_name='Primary NDC'),
        ),
        migrations.AlterField(
            model_name='part',
            name='IPN',
            field=models.CharField(help_text='Ticker Part Code', max_length=100, null=True, verbose_name='Code'),
        ),
    ]
