# Generated by Django 4.2.17 on 2025-03-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0134_remove_part_pharm_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='equipment_type',
            field=models.TextField(blank=True, default='', verbose_name='Equipment Type'),
        ),
        migrations.AlterField(
            model_name='part',
            name='IPN',
            field=models.CharField(blank=True, help_text='Ticker Part Code', max_length=100, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='part',
            name='auxillary_labels',
            field=models.CharField(blank=True, choices=[('May Cause Drowsiness', 'May Cause Drowsiness'), ('Shake Well', 'Shake Well'), ('Take with food', 'Take with food'), ('', '')], default='', help_text='Supplemental information', max_length=100, verbose_name='Auxillary Labels'),
        ),
    ]
